Add devise PR
kkasaija/blog-app pull request #9
Opened 2023-02-10 17:12 UTC by Kasaija-Kenneth

### Milestone reached

- Can register a new user.
- User logs in with a combination of email and password.
- Hashed password stored in the database.
- Ask for confirmation of email.
- Can reset password.

2023-02-10 18:24 UTC, Whoistolu requested changes
Hi @Kasaija-Kenneth 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Highlight
✔️ Removed `current_user` method in `ApplicationController`
✔️ Devise has been setup

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 18:24 UTC, Whoistolu commented on app/views/devise/registrations/new.html.erb
> +
- [ ] [REQUIRED] Great job so far @Kasaija-Kenneth , however, you need to ensure that the views in devise for the registration and login have been modified to match the wireframes and their styling. Kindly resolve this before asking for another review.

Your Implementation   |  Figma Design
:-------------------------:|:-------------------------:
<img width="297" alt="Screenshot 2023-02-10 at 19 08 53" src="https://user-images.githubusercontent.com/58692590/218165476-56f74607-7577-40b2-b9f2-0652ed139c51.png"> | <img width="423" alt="Screenshot 2023-02-10 at 18 58 48" src="https://user-images.githubusercontent.com/58692590/218165539-4110b778-cefb-4cc2-9ed3-823f24fef5b2.png">

2023-02-11 01:24 UTC, OLIPLICHE approved these changes
Hi @Kasaija-Kenneth, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Apply the change requested by the previous review👏 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-11 07:59 UTC, Kasaija-Kenneth commented
Thanks @OLIPLICHE

2023-02-11 08:00 UTC, merged